# Generated by Django 4.2.4 on 2023-08-28 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("siteApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="siteApp.student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="pin",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
