# Generated by Django 4.2.4 on 2023-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteApp", "0002_alter_attendance_present_alter_attendance_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(default=None, max_length=255, null=True)),
                (
                    "longitude",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("latitude", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
