# Generated by Django 4.2.4 on 2023-08-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteApp", "0003_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
