# Generated by Django 4.2.4 on 2023-08-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteApp", "0004_alter_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="classes_present",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="total_classes",
            field=models.IntegerField(default=24),
        ),
    ]
